# Generated by Django 5.0 on 2024-01-25 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Water',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oz', models.IntegerField(default=0)),
                ('time', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='sleep',
            name='awake',
            field=models.TextField(default='08:00'),
        ),
        migrations.AddField(
            model_name='sleep',
            name='time',
            field=models.TimeField(auto_now_add=True, default='21:10:46.866141'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='caffeine',
            name='time',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='time',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sleep',
            name='quality',
            field=models.IntegerField(default=1),
        ),
    ]
