# Generated by Django 5.0 on 2024-01-25 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_water_sleep_awake_sleep_time_alter_caffeine_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caffeine',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sleep',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='water',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
