# Generated by Django 5.0 on 2024-01-31 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_focus_mood_screentime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='focus',
            old_name='quality',
            new_name='focus',
        ),
        migrations.RenameField(
            model_name='mood',
            old_name='awake',
            new_name='mood',
        ),
    ]
